theme = "autumn"

[editor]
mouse = true
color-modes = true
auto-pairs = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
